//! Pure codegen (`generate`) plus the CLI-facing I/O wrapper (`run`) for the `codegen`
//! verb. See Context's "Determinism" subsection for the four rules `generate` must
//! follow — restated as doc comments on the function itself below.

use super::reports::{BlocksReport, RegistriesReport, find_default_state_id};

/// `xtask`'s own crate version, tagged as this codegen format's identity — written
/// into every `MANIFEST.json` entry's `generator_tool_version` field.
pub const CODEGEN_TOOL_VERSION: &str = concat!("xtask-codegen/", env!("CARGO_PKG_VERSION"));

pub struct GeneratedFiles {
    /// `(relative filename under crates/registries/generated/v<protocol_version>/, content)`,
    /// in write order: `("registries.rs", ...)`, `("block_states.rs", ...)`.
    pub files: Vec<(String, String)>,
}

fn strip_namespace(id: &str) -> &str {
    id.split_once(':').map(|(_, path)| path).unwrap_or(id)
}

fn sanitize_mod_name(path: &str) -> String {
    let mut s: String = path
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    if is_rust_keyword(&s) {
        s.push('_');
    }
    s
}

fn sanitize_const_name(path: &str) -> String {
    // SCREAMING_SNAKE_CASE output never collides with a Rust keyword (keywords are
    // always lowercase), so no keyword guard is needed here. It CAN collide with
    // `generate_registries_rs`'s own reserved per-module `COUNT` aggregate constant —
    // real 26.2 data confirms this happens (`minecraft:worldgen/placement_modifier_type`
    // registers an entry literally named "count") — so that one reserved identifier
    // gets the same trailing-underscore escape `sanitize_mod_name` already uses for
    // keyword collisions.
    let mut s: String = path
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    if s == "COUNT" {
        s.push('_');
    }
    s
}

fn is_rust_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "try"
    )
}

fn generate_registries_rs(registries: &RegistriesReport) -> String {
    let mut out = String::new();
    out.push_str("//! Generated by `xtask codegen` — do not edit by hand, re-run instead.\n");
    out.push_str("//!\n");
    out.push_str(
        "//! NET-D9/NET-D10: registry entry ID<->name tables, derived from `--reports`'\n",
    );
    out.push_str(
        "//! `registries.json` as processed, code-generated Rust source (never raw Mojang JSON).\n\n",
    );
    out.push_str("#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    out.push_str("pub struct RegistryEntryId(pub u32);\n\n");

    for (registry_name, report) in registries {
        let mod_name = sanitize_mod_name(strip_namespace(registry_name));
        let mut entries: Vec<(&String, u32)> = report
            .entries
            .iter()
            .map(|(name, entry)| (name, entry.protocol_id))
            .collect();
        entries.sort_by_key(|(_, id)| *id);

        out.push_str(&format!("pub mod {mod_name} {{\n"));
        out.push_str("    use super::RegistryEntryId;\n\n");
        for (entry_name, protocol_id) in &entries {
            let const_name = sanitize_const_name(strip_namespace(entry_name));
            out.push_str(&format!(
                "    pub const {const_name}: RegistryEntryId = RegistryEntryId({protocol_id});\n"
            ));
        }
        out.push_str(&format!(
            "\n    pub const COUNT: u32 = {};\n",
            entries.len()
        ));
        out.push_str("}\n\n");
    }

    out
}

fn generate_block_states_rs(blocks: &BlocksReport) -> String {
    let mut out = String::new();
    out.push_str("//! Generated by `xtask codegen` — do not edit by hand, re-run instead.\n");
    out.push_str("//!\n");
    out.push_str(
        "//! NET-D9/NET-D10: block-state ID tables, derived from `--reports`' `blocks.json`\n",
    );
    out.push_str("//! as processed, code-generated Rust source (never raw Mojang JSON).\n\n");
    out.push_str("#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    out.push_str("pub struct BlockStateId(pub u32);\n\n");

    let block_state_count: usize = blocks.values().map(|b| b.states.len()).sum();
    out.push_str(&format!(
        "pub const BLOCK_TYPE_COUNT: u32 = {};\n",
        blocks.len()
    ));
    out.push_str(&format!(
        "pub const BLOCK_STATE_COUNT: u32 = {block_state_count};\n\n"
    ));

    out.push_str("pub mod default_state {\n");
    out.push_str("    use super::BlockStateId;\n\n");
    for (block_name, block) in blocks {
        let const_name = sanitize_const_name(strip_namespace(block_name));
        let default_id = find_default_state_id(block)
            .expect("every real block report entry has exactly one default state");
        out.push_str(&format!(
            "    pub const {const_name}: BlockStateId = BlockStateId({default_id});\n"
        ));
    }
    out.push_str("}\n");

    out
}

/// M1-B04's own hand-authored, minecraft.wiki-sourced (verified 2026-08-21) list of every
/// `WORLDGEN`-layer registry — the registries Registry Data (`0x07`) ever transmits, never
/// the protocol-version-fixed `STATIC`-layer registries `registries.rs` already covers.
/// Re-verify against the real fetched `reports/registries.json` before every codegen
/// re-run that adds or removes a registry (blueprint Constraints (f)) — not sacred.
pub const WORLDGEN_REGISTRIES: &[&str] = &[
    "minecraft:banner_pattern",
    "minecraft:chat_type",
    "minecraft:damage_type",
    "minecraft:dialog",
    "minecraft:dimension_type",
    "minecraft:enchantment",
    "minecraft:instrument",
    "minecraft:jukebox_song",
    "minecraft:painting_variant",
    "minecraft:sulfur_cube_archetype",
    "minecraft:test_environment",
    "minecraft:test_instance",
    "minecraft:timeline",
    "minecraft:trim_material",
    "minecraft:trim_pattern",
    "minecraft:world_clock",
    "minecraft:worldgen/biome",
    "minecraft:cat_variant",
    "minecraft:cat_sound_variant",
    "minecraft:chicken_variant",
    "minecraft:chicken_sound_variant",
    "minecraft:cow_variant",
    "minecraft:cow_sound_variant",
    "minecraft:frog_variant",
    "minecraft:pig_variant",
    "minecraft:pig_sound_variant",
    "minecraft:wolf_variant",
    "minecraft:wolf_sound_variant",
    "minecraft:zombie_nautilus_variant",
];

/// Pure: for each name in `WORLDGEN_REGISTRIES`, look up `registries.get(name)` — absent
/// panics naming the missing registry (a loud, implementation-time-only failure). Collects
/// `(entry_name, protocol_id)` pairs, sorts by `protocol_id` (identical determinism rule
/// to `generate_registries_rs`), and emits one `pub mod { pub const ENTRIES: &[&str] }` per
/// registry — entry strings written in full, unsanitized (they are string literals, not
/// identifiers, so need no identifier-safety transform, unlike `registries.rs`'s own
/// `sanitize_const_name`-based output) — followed by one closing
/// `pub static REGISTRIES: &[(&str, &[&str])]` in `WORLDGEN_REGISTRIES`'s own fixed order.
///
/// `pub`, not private — `xtask/tests/datagen_codegen.rs`'s own
/// `registry_entries_panics_on_missing_worldgen_registry` case calls this directly (not
/// through `generate`) to observe the missing-registry panic in isolation, which requires
/// external visibility from that separate integration-test crate.
pub fn generate_registry_entries_rs(registries: &RegistriesReport) -> String {
    let mut out = String::new();
    out.push_str("//! Generated by `xtask codegen` — do not edit by hand, re-run instead.\n");
    out.push_str("//!\n");
    out.push_str("//! M1-B04: the exact original identifier string for every entry of every\n");
    out.push_str("//! WORLDGEN-layer registry, derived from `--reports`' `registries.json` as\n");
    out.push_str("//! processed, code-generated Rust source (never raw Mojang JSON).\n\n");

    for name in WORLDGEN_REGISTRIES {
        let report = registries
            .get(*name)
            .unwrap_or_else(|| panic!("WORLDGEN_REGISTRIES names {name:?}, absent from the real registries report — re-verify the list against reports/registries.json"));
        let mut entries: Vec<(&String, u32)> = report
            .entries
            .iter()
            .map(|(entry_name, entry)| (entry_name, entry.protocol_id))
            .collect();
        entries.sort_by_key(|(_, id)| *id);

        let mod_name = sanitize_mod_name(strip_namespace(name));
        out.push_str(&format!("pub mod {mod_name} {{\n"));
        out.push_str("    pub const ENTRIES: &[&str] = &[\n");
        for (entry_name, _) in &entries {
            out.push_str(&format!("        {entry_name:?},\n"));
        }
        out.push_str("    ];\n");
        out.push_str("}\n\n");
    }

    out.push_str("pub static REGISTRIES: &[(&str, &[&str])] = &[\n");
    for name in WORLDGEN_REGISTRIES {
        let mod_name = sanitize_mod_name(strip_namespace(name));
        out.push_str(&format!("    ({name:?}, {mod_name}::ENTRIES),\n"));
    }
    out.push_str("];\n");

    out
}

/// Pure transform: `--reports` data in, generated Rust source out. No filesystem
/// access. Deterministic per Context's four rules: parses/iterates only via `BTreeMap`
/// (never `HashMap`), sorts registry entries by `protocol_id` explicitly, embeds no
/// timestamp anywhere, and sanitizes identifiers as a pure function of the input
/// string alone. Two logically-identical `RegistriesReport`/`BlocksReport` values
/// (even if built via `.insert()` calls in different orders) MUST produce byte-
/// identical `GeneratedFiles::files` content — this is the property
/// `output_is_independent_of_input_insertion_order` (Acceptance tests) checks.
pub fn generate(registries: &RegistriesReport, blocks: &BlocksReport) -> GeneratedFiles {
    GeneratedFiles {
        files: vec![
            (
                "registries.rs".to_string(),
                generate_registries_rs(registries),
            ),
            (
                "block_states.rs".to_string(),
                generate_block_states_rs(blocks),
            ),
            (
                "registry_entries.rs".to_string(),
                generate_registry_entries_rs(registries),
            ),
        ],
    }
}

pub struct CodegenArgs {
    /// Directory containing `registries.json`/`blocks.json` (a prior `fetch-data`
    /// run's `datagen-output/<version>/generated/reports/` — M0-B08's shared
    /// `fetch_data::run_data_reports`'s own return path, reused as-is).
    pub reports_dir: std::path::PathBuf,
    /// `crates/registries/generated/v<protocol_version>/` — created if absent.
    pub out_dir: std::path::PathBuf,
    pub source_jar_sha1: String,
    pub protocol_version: u32,
    pub mc_version: String,
}

fn read_report_file(dir: &std::path::Path, name: &str, version: &str) -> Result<String, String> {
    let path = dir.join(name);
    std::fs::read_to_string(&path).map_err(|_| {
        format!(
            "missing {name} under {} — run `cargo xtask fetch-data {version}` first",
            dir.display()
        )
    })
}

/// I/O wrapper: reads `registries.json`+`blocks.json` from `args.reports_dir` (`Err`
/// naming the exact missing file and suggesting `cargo xtask fetch-data <version>` if
/// either is absent), calls `generate`, writes both files plus `MANIFEST.json` under
/// `args.out_dir`, then immediately calls `fixture_manifest::verify_manifest` against
/// what it just wrote as a self-check (defense against a write-time bug producing a
/// manifest that does not actually match the bytes on disk).
pub fn run(args: &CodegenArgs) -> Result<(), String> {
    let registries_json = read_report_file(&args.reports_dir, "registries.json", &args.mc_version)?;
    let blocks_json = read_report_file(&args.reports_dir, "blocks.json", &args.mc_version)?;

    let registries: RegistriesReport = serde_json::from_str(&registries_json)
        .map_err(|e| format!("failed to parse registries.json: {e}"))?;
    let blocks: BlocksReport = serde_json::from_str(&blocks_json)
        .map_err(|e| format!("failed to parse blocks.json: {e}"))?;

    let generated = generate(&registries, &blocks);

    std::fs::create_dir_all(&args.out_dir)
        .map_err(|e| format!("failed to create {}: {e}", args.out_dir.display()))?;

    let mut files_as_bytes: Vec<(String, Vec<u8>)> = Vec::with_capacity(generated.files.len());
    for (name, content) in &generated.files {
        let path = args.out_dir.join(name);
        std::fs::write(&path, content)
            .map_err(|e| format!("failed to write {}: {e}", path.display()))?;
        files_as_bytes.push((name.clone(), content.clone().into_bytes()));
    }

    let manifest = crate::fixture_manifest::build_manifest(
        args.protocol_version,
        &args.mc_version,
        &files_as_bytes,
        CODEGEN_TOOL_VERSION,
        &args.source_jar_sha1,
    );
    let manifest_json = serde_json::to_string_pretty(&manifest)
        .map_err(|e| format!("failed to serialize MANIFEST.json: {e}"))?;
    let manifest_path = args.out_dir.join("MANIFEST.json");
    std::fs::write(&manifest_path, &manifest_json)
        .map_err(|e| format!("failed to write {}: {e}", manifest_path.display()))?;

    let violations = crate::fixture_manifest::verify_manifest(&manifest_path, &args.out_dir);
    if !violations.is_empty() {
        let details: Vec<String> = violations
            .iter()
            .map(|v| format!("{} [{}]: {}", v.path, v.kind, v.message))
            .collect();
        return Err(format!(
            "codegen self-check failed — the manifest it just wrote does not match the files it just wrote: {}",
            details.join("; ")
        ));
    }

    Ok(())
}
