[package]
name = "rc-protocol-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"
arbitrary = { version = "1.4.2", features = ["derive"] }
bytes = "1.12.1"

[dependencies.rc-protocol]
path = ".."

[[bin]]
name = "decode_frame"
path = "fuzz_targets/decode_frame.rs"
test = false
doc = false

[[bin]]
name = "varint_decode"
path = "fuzz_targets/varint_decode.rs"
test = false
doc = false

[workspace]
